# Generated by Django 3.2.5 on 2021-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.CharField(max_length=70)),
                ('sid', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('age', models.CharField(max_length=70)),
                ('cls', models.CharField(max_length=70)),
            ],
        ),
    ]
