# Generated by Django 3.2.6 on 2021-08-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210803_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewattendance',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
