# Generated by Django 3.2.5 on 2021-08-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_viewattendance_date_of_attend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewattendance',
            name='student_id',
        ),
        migrations.AddField(
            model_name='viewattendance',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewattendance',
            name='username',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
