# Generated by Django 3.2.5 on 2021-08-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210804_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('date_of_leave', models.DateField(max_length=70)),
                ('type_of_leave', models.CharField(choices=[('C', 'Casual Leave'), ('L', 'Loss of Pay'), ('S', 'Sick Leave')], max_length=70)),
                ('message', models.CharField(max_length=70)),
            ],
        ),
    ]
